## Serenity specific configuration
serenity.take.screenshots=AFTER_EACH_STEP
ignore.failures.in.stories=true
webdriver.timeouts.implicitlywait=10000
story.timeout.in.secs=3000
serenity.restart.browser.for.each=EXAMPLE


## Browser specific configuration
webdriver.base.url=https://bookdepository.com/
webdriver.driver=chrome
headless.mode=true
chrome.switches=--incognito
serenity.browser.width=1600
serenity.browser.height=1000

